// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto

#include "test.pb.h"
#include "test.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace rpcpb {

static const char* Base_method_names[] = {
  "/rpcpb.Base/Health",
};

std::unique_ptr< Base::Stub> Base::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Base::Stub> stub(new Base::Stub(channel));
  return stub;
}

Base::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Health_(Base_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Base::Stub::Health(::grpc::ClientContext* context, const ::rpcpb::HealthReq& request, ::rpcpb::HealthRsp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Health_, context, request, response);
}

void Base::Stub::experimental_async::Health(::grpc::ClientContext* context, const ::rpcpb::HealthReq* request, ::rpcpb::HealthRsp* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::rpcpb::HealthRsp>* Base::Stub::AsyncHealthRaw(::grpc::ClientContext* context, const ::rpcpb::HealthReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::rpcpb::HealthRsp>::Create(channel_.get(), cq, rpcmethod_Health_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::rpcpb::HealthRsp>* Base::Stub::PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::rpcpb::HealthReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::rpcpb::HealthRsp>::Create(channel_.get(), cq, rpcmethod_Health_, context, request, false);
}

Base::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Base_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Base::Service, ::rpcpb::HealthReq, ::rpcpb::HealthRsp>(
          std::mem_fn(&Base::Service::Health), this)));
}

Base::Service::~Service() {
}

::grpc::Status Base::Service::Health(::grpc::ServerContext* context, const ::rpcpb::HealthReq* request, ::rpcpb::HealthRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rpcpb

