// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_INCLUDED_test_2eproto
#define PROTOBUF_INCLUDED_test_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_test_2eproto 

namespace protobuf_test_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_test_2eproto
namespace rpcpb {
class HealthReq;
class HealthReqDefaultTypeInternal;
extern HealthReqDefaultTypeInternal _HealthReq_default_instance_;
class HealthRsp;
class HealthRspDefaultTypeInternal;
extern HealthRspDefaultTypeInternal _HealthRsp_default_instance_;
}  // namespace rpcpb
namespace google {
namespace protobuf {
template<> ::rpcpb::HealthReq* Arena::CreateMaybeMessage<::rpcpb::HealthReq>(Arena*);
template<> ::rpcpb::HealthRsp* Arena::CreateMaybeMessage<::rpcpb::HealthRsp>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace rpcpb {

// ===================================================================

class HealthReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpcpb.HealthReq) */ {
 public:
  HealthReq();
  virtual ~HealthReq();

  HealthReq(const HealthReq& from);

  inline HealthReq& operator=(const HealthReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HealthReq(HealthReq&& from) noexcept
    : HealthReq() {
    *this = ::std::move(from);
  }

  inline HealthReq& operator=(HealthReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HealthReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HealthReq* internal_default_instance() {
    return reinterpret_cast<const HealthReq*>(
               &_HealthReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(HealthReq* other);
  friend void swap(HealthReq& a, HealthReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HealthReq* New() const final {
    return CreateMaybeMessage<HealthReq>(NULL);
  }

  HealthReq* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HealthReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HealthReq& from);
  void MergeFrom(const HealthReq& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HealthReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:rpcpb.HealthReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HealthRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpcpb.HealthRsp) */ {
 public:
  HealthRsp();
  virtual ~HealthRsp();

  HealthRsp(const HealthRsp& from);

  inline HealthRsp& operator=(const HealthRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HealthRsp(HealthRsp&& from) noexcept
    : HealthRsp() {
    *this = ::std::move(from);
  }

  inline HealthRsp& operator=(HealthRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HealthRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HealthRsp* internal_default_instance() {
    return reinterpret_cast<const HealthRsp*>(
               &_HealthRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(HealthRsp* other);
  friend void swap(HealthRsp& a, HealthRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HealthRsp* New() const final {
    return CreateMaybeMessage<HealthRsp>(NULL);
  }

  HealthRsp* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HealthRsp>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HealthRsp& from);
  void MergeFrom(const HealthRsp& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HealthRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  const ::std::string& result() const;
  void set_result(const ::std::string& value);
  #if LANG_CXX11
  void set_result(::std::string&& value);
  #endif
  void set_result(const char* value);
  void set_result(const char* value, size_t size);
  ::std::string* mutable_result();
  ::std::string* release_result();
  void set_allocated_result(::std::string* result);

  // @@protoc_insertion_point(class_scope:rpcpb.HealthRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr result_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HealthReq

// -------------------------------------------------------------------

// HealthRsp

// string result = 1;
inline void HealthRsp::clear_result() {
  result_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HealthRsp::result() const {
  // @@protoc_insertion_point(field_get:rpcpb.HealthRsp.result)
  return result_.GetNoArena();
}
inline void HealthRsp::set_result(const ::std::string& value) {
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rpcpb.HealthRsp.result)
}
#if LANG_CXX11
inline void HealthRsp::set_result(::std::string&& value) {
  
  result_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rpcpb.HealthRsp.result)
}
#endif
inline void HealthRsp::set_result(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rpcpb.HealthRsp.result)
}
inline void HealthRsp::set_result(const char* value, size_t size) {
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rpcpb.HealthRsp.result)
}
inline ::std::string* HealthRsp::mutable_result() {
  
  // @@protoc_insertion_point(field_mutable:rpcpb.HealthRsp.result)
  return result_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HealthRsp::release_result() {
  // @@protoc_insertion_point(field_release:rpcpb.HealthRsp.result)
  
  return result_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HealthRsp::set_allocated_result(::std::string* result) {
  if (result != NULL) {
    
  } else {
    
  }
  result_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), result);
  // @@protoc_insertion_point(field_set_allocated:rpcpb.HealthRsp.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpcpb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_test_2eproto
